name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install ruff

    - name: Run code quality checks
      run: |
        cd fenix-eagle && ruff check .
        cd ../fenix-gateway && ruff check .

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        debug: true
        use_insecure_cipher: false
        script: |
          # Check OS and install git if not present
          if ! command -v git &> /dev/null; then
            echo "Git not found, attempting to install..."
            if command -v apt-get &> /dev/null; then
              apt-get update && apt-get install -y git
            elif command -v yum &> /dev/null; then
              yum install -y git
            elif command -v apk &> /dev/null; then
              apk add --no-cache git
            else
              echo "ERROR: Cannot install git - unknown package manager"
              exit 1
            fi
          fi

          # Check if project directory exists, create if not
          if [ ! -d /root/FENIX ]; then
            cd /root
            git clone https://github.com/${{ github.repository }}.git FENIX
            cd FENIX
          else
            cd /root/FENIX
            git pull origin main
          fi

          # Copy .env.example to .env if .env doesn't exist
          if [ ! -f .env ]; then
            if [ -f .env.example ]; then
              cp .env.example .env
            else
              echo "WARNING: .env.example not found, creating minimal .env"
              touch .env
            fi
          fi

          # Update .env with secrets (only if secrets are set)
          if [ -n "${{ secrets.SAM_GOV_API_KEY }}" ]; then
            sed -i 's/SAM_GOV_API_KEY=.*/SAM_GOV_API_KEY=${{ secrets.SAM_GOV_API_KEY }}/' .env
          fi
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            sed -i 's/OPENAI_API_KEY=.*/OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}/' .env
          fi
          if [ -n "${{ secrets.CRAWL4AI_API_KEY }}" ]; then
            sed -i 's/CRAWL4AI_API_KEY=.*/CRAWL4AI_API_KEY=${{ secrets.CRAWL4AI_API_KEY }}/' .env
          fi
          if [ -n "${{ secrets.SHOVELS_AI_API_KEY }}" ]; then
            sed -i 's/SHOVELS_AI_API_KEY=.*/SHOVELS_AI_API_KEY=${{ secrets.SHOVELS_AI_API_KEY }}/' .env
          fi

          # E-mail configuration (only if secrets are set)
          if [ -n "${{ secrets.SMTP_SERVER }}" ]; then
            sed -i 's/SMTP_SERVER=.*/SMTP_SERVER=${{ secrets.SMTP_SERVER }}/' .env
          fi
          if [ -n "${{ secrets.SMTP_PORT }}" ]; then
            sed -i 's/SMTP_PORT=.*/SMTP_PORT=${{ secrets.SMTP_PORT }}/' .env
          fi
          if [ -n "${{ secrets.EMAIL_USERNAME }}" ]; then
            sed -i 's/EMAIL_USERNAME=.*/EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}/' .env
          fi
          if [ -n "${{ secrets.EMAIL_PASSWORD }}" ]; then
            sed -i 's/EMAIL_PASSWORD=.*/EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}/' .env
          fi
          if [ -n "${{ secrets.DEFAULT_NOTIFICATION_EMAIL }}" ]; then
            sed -i 's/DEFAULT_NOTIFICATION_EMAIL=.*/DEFAULT_NOTIFICATION_EMAIL=${{ secrets.DEFAULT_NOTIFICATION_EMAIL }}/' .env
          fi

          # Force overwrite .env with our current configuration to ensure source flags are set
          echo "$(date): Updating .env configuration..." >> /var/log/fenix-deploy.log
          cp .env.example .env

          # Re-apply secrets to the fresh .env file
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            sed -i 's/OPENAI_API_KEY=.*/OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}/' .env
          fi
          if [ -n "${{ secrets.EMAIL_USERNAME }}" ]; then
            sed -i 's/EMAIL_USERNAME=.*/EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}/' .env
          fi
          if [ -n "${{ secrets.EMAIL_PASSWORD }}" ]; then
            sed -i 's/EMAIL_PASSWORD=.*/EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}/' .env
          fi
          if [ -n "${{ secrets.DEFAULT_NOTIFICATION_EMAIL }}" ]; then
            sed -i 's/DEFAULT_NOTIFICATION_EMAIL=.*/DEFAULT_NOTIFICATION_EMAIL=${{ secrets.DEFAULT_NOTIFICATION_EMAIL }}/' .env
          fi

          # Run deployment with modern docker compose
          echo "$(date): Starting FENIX deployment with data preservation..." >> /var/log/fenix-deploy.log

          # Create volumes if needed (before any operations)
          docker volume create fenix_postgres_data || true
          docker volume create fenix_redis_data || true

          # CRITICAL: Create database backup before any changes
          echo "$(date): Creating database backup..." >> /var/log/fenix-deploy.log
          if docker compose ps postgres | grep -q "Up"; then
            mkdir -p /root/fenix-backups
            BACKUP_FILE="/root/fenix-backups/fenix-backup-$(date +%Y%m%d-%H%M%S).sql"
            docker compose exec -T postgres pg_dump -U fenix fenix > "$BACKUP_FILE" 2>/dev/null || echo "Backup failed - continuing deployment"
            echo "$(date): Database backed up to $BACKUP_FILE" >> /var/log/fenix-deploy.log
          fi

          # Build new images WITHOUT stopping database
          echo "$(date): Building Docker images..." >> /var/log/fenix-deploy.log
          docker compose build --no-cache 2>&1 | tee -a /var/log/fenix-deploy.log

          # SAFE DEPLOYMENT: Rolling update without destroying database
          echo "$(date): Performing rolling update..." >> /var/log/fenix-deploy.log

          # Stop only application services, KEEP database running
          docker compose stop eagle gateway core oracle shield archer bolt dashboard 2>&1 | tee -a /var/log/fenix-deploy.log || true

          # Start services with new images (database keeps running)
          echo "$(date): Starting updated services..." >> /var/log/fenix-deploy.log
          docker compose up -d 2>&1 | tee -a /var/log/fenix-deploy.log

          # Wait for database to be healthy
          echo "$(date): Waiting for database to be healthy..." >> /var/log/fenix-deploy.log
          timeout=60
          while [ $timeout -gt 0 ]; do
            if docker compose exec postgres pg_isready -U fenix > /dev/null 2>&1; then
              echo "$(date): Database is ready!" >> /var/log/fenix-deploy.log
              break
            fi
            sleep 2
            timeout=$((timeout-2))
          done

          # Check all services
          docker compose ps

          # Test monitoring system and verify data integrity
          sleep 10
          if curl -s http://localhost:8001/health > /dev/null; then
            echo "$(date): Eagle service is healthy" >> /var/log/fenix-deploy.log

            # Check if we have data in database
            TENDER_COUNT=$(curl -s http://localhost:8001/monitoring/stats | grep -o '"total_tenders":[0-9]*' | cut -d':' -f2 || echo "0")
            echo "$(date): Database contains $TENDER_COUNT tenders after deployment" >> /var/log/fenix-deploy.log

            if [ "$TENDER_COUNT" = "0" ] && [ -n "$(ls /root/fenix-backups/*.sql 2>/dev/null | tail -1)" ]; then
              echo "$(date): WARNING - No tenders found after deployment! Latest backup available for restore." >> /var/log/fenix-deploy.log
            fi
          else
            echo "$(date): ERROR - Eagle service not responding after deployment!" >> /var/log/fenix-deploy.log
          fi

          echo "$(date): Deployment completed with data preservation!" >> /var/log/fenix-deploy.log

    - name: Notify deployment status
      if: always()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        debug: true
        script: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "$(date): GitHub Actions deployment successful" >> /var/log/fenix-deploy.log
          else
            echo "$(date): GitHub Actions deployment failed" >> /var/log/fenix-deploy.log
          fi
