name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Install git if not present
          if ! command -v git &> /dev/null; then
            apt-get update && apt-get install -y git
          fi
          
          # Check if project directory exists, create if not
          if [ ! -d /root/fenix ]; then
            cd /root
            git clone https://github.com/${{ github.repository }}.git fenix
            cd fenix
          else
            cd /root/fenix
            git pull origin main
          fi
          
          # Copy .env.example to .env if .env doesn't exist
          if [ ! -f .env ]; then
            cp .env.example .env
          fi
          
          # Run deployment with modern docker compose
          docker compose down || true
          docker compose build
          docker compose up -d
          docker compose ps
          
    - name: Notify deployment status
      if: always()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "$(date): GitHub Actions deployment successful" >> /var/log/fenix-deploy.log
          else
            echo "$(date): GitHub Actions deployment failed" >> /var/log/fenix-deploy.log
          fi